Add Seed Data
StemboltHQ/staff_tracker pull request #20
Opened 2017-02-24 19:38 UTC by gregdaynes

Seed data for interacting with the application on development.

2017-02-24 22:09 UTC, graygilmore requested changes

2017-02-24 22:09 UTC, graygilmore commented on db/seeds.rb
>  #   Character.create(name: 'Luke', movie: movies.first)
While we're in here we might as well nuke these comments.

2017-02-24 22:09 UTC, graygilmore commented on db/seeds.rb
> +  people.push(person)
I don't think we need to be story these in an array. Later on when you want to select a random user you could do something like:

```ruby
person_id: Person.pluck(:id).sample
```

This logic can apply to all of the seeds.

2017-02-27 16:36 UTC, gregdaynes commented on db/seeds.rb
> +  people.push(person)
.sample is amazing!

2017-02-27 18:38 UTC, qr8r approved these changes

2017-02-27 21:55 UTC, graygilmore approved these changes

2017-02-27 21:56 UTC, merged