Feature/flash messages
StemboltHQ/staff_tracker pull request #58
Opened 2017-03-28 21:04 UTC by natyork

Create a view to render all flash messages per https://www.pivotaltracker.com/story/show/142562277

Flash messages will be displayed in a div with `class="alert alert-#{key}"` where key is the flash type, so flash messages can be styled by type.

There are no custom flash types currently defined, but if in future custom flash methods are defined, such as for https://www.pivotaltracker.com/story/show/142092195 they can be defined in the applications controller per: http://api.rubyonrails.org/classes/ActionController/Flash/ClassMethods.html

2017-03-28 21:42 UTC, graygilmore requested changes
We can squash the two commits into one as they don't make sense without each other.

2017-03-28 21:42 UTC, graygilmore commented on app/views/layouts/_flash-messages.html.erb
> +<div class='alert-container'>
Should we have a conditional here like `if flash.any?`?

2017-03-29 15:31 UTC, jacquesporveau approved these changes
LGTM besides Grays comment.

2017-03-29 16:19 UTC, natyork commented
Commits squashed and conditional rendering of flash messages added per @graygilmore comments.

2017-03-29 16:48 UTC, qr8r approved these changes

2017-03-29 21:16 UTC, natyork commented
@graygilmore has moved this story to the icebox. I am going to close this PR.

2017-03-29 21:17 UTC, graygilmore approved these changes

2017-03-29 21:17 UTC, graygilmore commented
Merging ❤️

2017-03-29 21:17 UTC, merged