Feature/auto populate
StemboltHQ/staff_tracker pull request #59
Opened 2017-03-28 22:59 UTC by jacquesporveau

https://www.pivotaltracker.com/story/show/141823283

2017-03-28 23:48 UTC, graygilmore requested changes

2017-03-28 23:48 UTC, graygilmore commented on spec/models/event_spec.rb
> +    subject(:event_upcoming?) { event.upcoming? }
If you're not going to use the named subject you can just do `subject { event.upcoming? }`.

2017-03-28 23:48 UTC, graygilmore commented on spec/models/event_spec.rb
> +        FactoryGirl.create(:event, date: Time.zone.today + 1.hour)
Instead of doing math you could do something like: `1.year.from_now`.

2017-03-28 23:48 UTC, graygilmore commented on spec/models/event_spec.rb
> +        FactoryGirl.create(:event, date: Time.zone.today + 1.hour)
Can we get away with using `build` here? Might not get picked up by the scope, I guess.

2017-03-28 23:48 UTC, graygilmore commented on app/views/presentations/_sign_up_link.html.erb
> +    link_to 'Sign up', new_presentation_path(prepopulated_event: event.id)
Instead of `prepopulated_event` could we just use `event`? Or even `event_id` as that's what we're passing.

2017-03-29 00:01 UTC, jacquesporveau commented on spec/models/event_spec.rb
> +        FactoryGirl.create(:event, date: Time.zone.today + 1.hour)
Can't use build as it won't be picked up by scope.

2017-03-29 00:04 UTC, jacquesporveau commented on app/views/presentations/_sign_up_link.html.erb
> +    link_to 'Sign up', new_presentation_path(prepopulated_event: event.id)
Mmmmmm I kind of want there to be some reference to what this is for when it hits the controller.
This allows me to have `params[:prepopulated_event]` in my controller. I know what that is.
Having a reference to `params[:event_id]` in my presentations controller is kind of odd. Why do I have a reference to this? What is this being used for?

2017-03-29 16:23 UTC, brendandeere commented on app/models/event.rb
> +    Event.upcoming.include?(self)
this could also be `self.class`

2017-03-29 16:23 UTC, brendandeere commented on app/views/presentations/_sign_up_link.html.erb
> +    link_to 'Sign up', new_presentation_path(prepopulated_event: event.id)
So I have a question that is meant more for discussion: 

Does it ever make sense to create a presentation that is not associated to a specific event? 
Is there ever a time when Im trying to create a presentation that I dont already know specifically which event I want it to be associated with?

2017-03-29 16:34 UTC, jacquesporveau commented on app/views/presentations/_sign_up_link.html.erb
> +    link_to 'Sign up', new_presentation_path(prepopulated_event: event.id)
In the current state of the application? No. In the future? Maybe.

2017-03-29 16:53 UTC, brendandeere commented on app/views/presentations/_sign_up_link.html.erb
> +    link_to 'Sign up', new_presentation_path(prepopulated_event: event.id)
Cool, If it never makes sense to build a presentation in isolation form an event. Should presentations then be a nested resource of events?

2017-03-29 16:57 UTC, jacquesporveau commented on app/views/presentations/_sign_up_link.html.erb
> +    link_to 'Sign up', new_presentation_path(prepopulated_event: event.id)
I see where you are going with this and I like it.

2017-03-29 17:31 UTC, jacquesporveau commented on app/models/event.rb
> +    Event.upcoming.include?(self)
I think you are trying to lead me to: If we changed the name of the class in the future we wouldn't need to update this method. I am going to take the advice.

2017-03-29 18:15 UTC, jacquesporveau commented
I am going to be tackling this a completely different way so I am going to close this PR.

2017-03-29 18:15 UTC, closed without merging