Feature/request presentations
StemboltHQ/staff_tracker pull request #63
Opened 2017-03-30 16:48 UTC by jacquesporveau

**Dependent on #62**. Set to merge into #62 to view a clean diff. Don't merge until the compared branch has been updated to master and #62 is merged.

Part two of https://www.pivotaltracker.com/story/show/140356337

2017-03-31 22:53 UTC, graygilmore requested changes

2017-03-31 22:53 UTC, graygilmore commented on app/controllers/topic_requests_controller.rb
> +    flash[:notice] = if topic_request.save
Should we do a `flash[:success]` and `flash[:error]` instead?

2017-03-31 22:53 UTC, graygilmore commented on app/controllers/topic_requests_controller.rb
> +    redirect_to requests_presentations_path
If we do a redirect here do we get specific error messages for why it wasn't submitted? Like if the user leaves it blank.

2017-03-31 22:53 UTC, graygilmore commented on app/policies/topic_request_policy.rb
> +    true
Should we skip this entirely and just not do `authorize topic_request`?

2017-03-31 22:53 UTC, graygilmore commented on spec/policies/topic_request_policy_spec.rb
> +    describe '#create?' do
I think this spec file is a little backwards. Normally you'd see something like:

```ruby
describe "#my_method" do
  subject { my_method }

  it "does something" do
  end

  context "context one" do
    it "does another thing" do
    end
  end

  context "context two" do
    it "does something else" do
    end
  end
end
```

2017-04-03 16:28 UTC, jacquesporveau commented on app/controllers/topic_requests_controller.rb
> +    redirect_to requests_presentations_path
Yes it did do that.

2017-04-03 16:28 UTC, jacquesporveau commented on app/policies/topic_request_policy.rb
> +    true
Yes we should. Done now.

2017-04-03 16:29 UTC, jacquesporveau commented on spec/policies/topic_request_policy_spec.rb
> +    describe '#create?' do
Point taken. This code has all been removed along with the policy it was testing though.

2017-04-03 18:37 UTC, natyork reviewed
Looks good to me :) Nice work!

2017-04-04 17:51 UTC, jacquesporveau commented on app/controllers/topic_requests_controller.rb
> +    flash[:notice] = if topic_request.save
:+1:

2017-04-04 17:55 UTC, graygilmore approved these changes

2017-04-04 23:39 UTC, merged