Feature/conditional-links
StemboltHQ/staff_tracker pull request #69
Opened 2017-04-03 21:18 UTC by natyork

Render links requiring authorization conditionally per https://www.pivotaltracker.com/story/show/142421857

Note, there are currently no policies applied to PeopleController, therefore the links on People#index and People#show have not been updated. I have created a new story in the icebox to update the authorizations for PeopleController, including conditionally rendering links on the associated views (https://www.pivotaltracker.com/story/show/142992497)

2017-04-03 22:37 UTC, graygilmore commented on app/views/events/_event.html.erb
> +    <% if current_person&.admin? %>
Should this use the event policy instead?

2017-04-03 23:18 UTC, natyork commented on app/views/events/_event.html.erb
> +    <% if current_person&.admin? %>
Yes that makes sense - currently only an admin is permitted to edit/delete events, but if that changes in future, we wouldn't have to update the view.

2017-04-04 16:11 UTC, natyork commented
Updated per @graygilmore comments

2017-04-04 17:58 UTC, jacquesporveau requested changes
The spacing issue is required but the one line if statement is a preference thing that I'll leave up to you.

2017-04-04 17:58 UTC, jacquesporveau commented on app/views/events/_event.html.erb
> +    <%end%>
Spaces

2017-04-04 17:58 UTC, jacquesporveau commented on app/views/events/show.html.erb
> +<% end %>
`<%= link_to 'Edit', edit_event_path(@event) if policy(@event).edit? %>`

Could probably one line these. That one is 70 char.

2017-04-04 21:13 UTC, natyork commented
Updated per @jacquesporveau comments

2017-04-04 23:38 UTC, jacquesporveau requested changes

2017-04-04 23:38 UTC, jacquesporveau commented on app/views/events/_event.html.erb
> +    <%end%>
Expand your brackets... expand your life
`<% end %>`

2017-04-05 16:05 UTC, natyork commented
Updated per @jacquesporveau comment

2017-04-05 16:50 UTC, qr8r approved these changes

2017-04-05 20:43 UTC, jacquesporveau approved these changes

2017-04-05 21:30 UTC, merged