[WIP] - Feature/nested attributes
StemboltHQ/staff_tracker pull request #72
Opened 2017-04-05 21:39 UTC by jacquesporveau

2017-04-05 22:11 UTC, graygilmore requested changes
Holy moly this is such a great improvement. Awesome job.

2017-04-05 22:11 UTC, graygilmore commented on app/controllers/admin/people_controller.rb
> +      params.require(:people).permit(person: [role_ids: []])[:person]
💯 🔥

2017-04-05 22:11 UTC, graygilmore commented on spec/controllers/admin_controller_spec.rb
> +  describe '#authenticate_admin' do
I believe that the controllers that are actually executing this path should cover these tests already. @brendandeere what do you think about this testing a private method?

2017-04-05 22:11 UTC, graygilmore commented on spec/policies/person_policy_spec.rb
> +      it 'returns false' do
Could rewrite as `it { is_expected.to eq false }` if you want to shorten these.

2017-04-05 22:24 UTC, jacquesporveau commented on spec/controllers/admin_controller_spec.rb
> +  describe '#authenticate_admin' do
I've changed how this test was to implemented. The test now creates a mock controller that inherits from the admin controller. Then the tests test that controller.

2017-04-06 16:12 UTC, graygilmore commented on spec/controllers/admin_controller_spec.rb
> +  describe '#authenticate_admin' do
I think I'd still like Brendan's opinion. Testing a private method is counter to Stembolt convention.

2017-04-06 23:15 UTC, graygilmore commented on spec/controllers/admin_controller_spec.rb
> +  describe '#authenticate_admin' do
After talking to Brendan about this we'd like to make use of RSpec's shared examples. What we really care about here is that the controllers that inherit from `AdminController` contain that functionality.

We don't want to have to write the same specs out every time for each controller that inherits from `AdminController`, though. Fortunately shared examples let's us define a series of assertions for the admin controller and simply include them in each controller that inherits from it.

```ruby
RSpec.describe SomeController do
  it_behaves_like "an admin controller"
end

RSpec.describe SomeOtherController do
  it_behaves_like "an admin controller"
end
```

2017-04-07 17:17 UTC, jacquesporveau commented
jenkins test this please

2017-04-07 17:20 UTC, jacquesporveau commented
jenkins test this please

2017-05-29 20:02 UTC, closed without merging